const lessonTitle = "窃读记";

const lessonData = [
    // ===== 第1段 =====
    ["转过", "zhuǎn guò", "turned", "membelok"],
    ["街角", "jiē jiǎo", "street corner", "sudut jalan"],
    ["，", "", "", ""],
    ["看见", "kàn jiàn", "saw", "melihat"],
    ["三阳春", "sān yáng chūn", "Sanyangchun", "Sanyangchun"],
    ["的", "de", "", ""],
    ["冲天", "chōng tiān", "towering", "menjulang"],
    ["招牌", "zhāo pái", "signboard", "papan tanda"],
    ["，", "", "", ""],
    ["闻见", "wén jiàn", "smelled", "terhidu"],
    ["炒菜", "chǎo cài", "stir-fry", "masakan"],
    ["的", "de", "", ""],
    ["香味", "xiāng wèi", "fragrance", "bau harum"],
    ["，", "", "", ""],
    ["听见", "tīng jiàn", "heard", "terdengar"],
    ["锅勺", "guō sháo", "pots and spoons", "kuali dan senduk"],
    ["的", "de", "", ""],
    ["声音", "shēng yīn", "sound", "bunyi"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["松了", "sōng le", "let out", "melepaskan"],
    ["一口气", "yī kǒu qì", "a sigh of relief", "nafas lega"],
    ["，", "", "", ""],
    ["放慢了", "fàng màn le", "slowed down", "memperlahankan"],
    ["脚步", "jiǎo bù", "pace", "langkah"],
    ["。", "", "", ""],
    ["下课", "xià kè", "class dismissed", "selepas sekolah"],
    ["从", "cóng", "from", "dari"],
    ["学校", "xué xiào", "school", "sekolah"],
    ["急急", "jí jí", "hurriedly", "tergesa-gesa"],
    ["赶到", "gǎn dào", "rushed to", "berlari ke"],
    ["这里", "zhè lǐ", "here", "sini"],
    ["，", "", "", ""],
    ["身上", "shēn shàng", "my body", "badan"],
    ["已经", "yǐ jīng", "already", "sudah"],
    ["汗涔涔的", "hàn cén cén de", "drenched in sweat", "berpeluh-peluh"],
    ["，", "", "", ""],
    ["总算", "zǒng suàn", "finally", "akhirnya"],
    ["到达", "dào dá", "arrived", "sampai"],
    ["目的地", "mù dì dì", "destination", "destinasi"],
    ["——", "", "", ""],
    ["目的地", "mù dì dì", "destination", "destinasi"],
    ["可不是", "kě bú shì", "was not", "bukan"],
    ["三阳春", "sān yáng chūn", "Sanyangchun", "Sanyangchun"],
    ["，", "", "", ""],
    ["而是", "ér shì", "but rather", "tetapi"],
    ["紧邻", "jǐn lín", "next to", "bersebelahan"],
    ["它", "tā", "it", "ia"],
    ["的", "de", "", ""],
    ["一家", "yī jiā", "a", "sebuah"],
    ["书店", "shū diàn", "bookstore", "kedai buku"],
    ["。", "", "", ""],
    
    ["\n", "", "", ""], // 👈 第2段

    ["我", "wǒ", "I", "saya"],
    ["趁着", "chèn zhe", "taking advantage of", "sambil"],
    ["漫步", "màn bù", "strolling", "berjalan perlahan"],
    ["给", "gěi", "give", "memberi"],
    ["脑子", "nǎo zi", "mind", "fikiran"],
    ["一个", "yī gè", "a", "sebuah"],
    ["思索", "sī suǒ", "think", "berfikir"],
    ["的", "de", "", ""],
    ["机会", "jī huì", "chance", "peluang"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["昨天", "zuó tiān", "yesterday", "semalam"],
    ["读到", "dú dào", "read to", "baca sampai"],
    ["什么", "shén me", "what", "apa"],
    ["地方", "dì fang", "place", "tempat"],
    ["了", "le", "", ""],
    ["？", "", "", ""],
    ["那", "nà", "that", "itu"],
    ["女孩", "nǚ hái", "girl", "gadis"],
    ["不知", "bù zhī", "don't know", "entah"],
    ["以后", "yǐ hòu", "later", "nanti"],
    ["嫁给", "jià gěi", "marry", "kahwin dengan"],
    ["谁", "shuí", "who", "siapa"],
    ["？", "", "", ""],
    ["那", "nà", "that", "itu"],
    ["本书", "běn shū", "book", "buku"],
    ["放在", "fàng zài", "placed", "diletakkan di"],
    ["哪里", "nǎ lǐ", "where", "mana"],
    ["？", "", "", ""],
    ["左角", "zuǒ jiǎo", "left corner", "sudut kiri"],
    ["第三排", "dì sān pái", "third row", "baris ketiga"],
    ["，", "", "", ""],
    ["不错", "bù cuò", "right", "betul"],
    ["。", "", "", ""],
    ["……”", "", "", ""],
    ["走到", "zǒu dào", "reached", "sampai ke"],
    ["三阳春", "sān yáng chūn", "Sanyangchun", "Sanyangchun"],
    ["的", "de", "", ""],
    ["门口", "mén kǒu", "entrance", "pintu masuk"],
    ["，", "", "", ""],
    ["便", "biàn", "then", "lalu"],
    ["可以", "kě yǐ", "could", "boleh"],
    ["看见", "kàn jiàn", "see", "melihat"],
    ["书店里", "shū diàn lǐ", "in the bookstore", "di kedai buku"],
    ["仍", "réng", "still", "masih"],
    ["像", "xiàng", "like", "seperti"],
    ["往日", "wǎng rì", "before", "dulu"],
    ["一样", "yī yàng", "same", "sama"],
    ["挤满了", "jǐ mǎn le", "packed with", "penuh dengan"],
    ["顾客", "gù kè", "customers", "pelanggan"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["可以", "kě yǐ", "could", "boleh"],
    ["安心", "ān xīn", "feel at ease", "tenang"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["但是", "dàn shì", "but", "tetapi"],
    ["我", "wǒ", "I", "saya"],
    ["又", "yòu", "also", "juga"],
    ["担忧", "dān yōu", "worried", "bimbang"],
    ["那", "nà", "that", "itu"],
    ["本书", "běn shū", "book", "buku"],
    ["会不会", "huì bù huì", "whether", "sama ada"],
    ["卖光了", "mài guāng le", "sold out", "habis dijual"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["一连", "yī lián", "for several", "beberapa"],
    ["几天", "jǐ tiān", "days", "hari"],
    ["都", "dōu", "all", "semua"],
    ["看见", "kàn jiàn", "saw", "nampak"],
    ["有人", "yǒu rén", "people", "orang"],
    ["买", "mǎi", "buy", "beli"],
    ["，", "", "", ""],
    ["昨天", "zuó tiān", "yesterday", "semalam"],
    ["好像", "hǎo xiàng", "seemed", "nampaknya"],
    ["只剩下", "zhǐ shèng xià", "only left", "hanya tinggal"],
    ["一两本", "yī liǎng běn", "one or two copies", "satu dua naskhah"],
    ["了", "le", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    ["我", "wǒ", "I", "saya"],
    ["跨进", "kuà jìn", "stepped into", "melangkah masuk"],
    ["书店", "shū diàn", "bookstore", "kedai buku"],
    ["门", "mén", "door", "pintu"],
    ["，", "", "", ""],
    ["暗喜", "àn xǐ", "secretly glad", "gembira dalam hati"],
    ["没人", "méi rén", "no one", "tiada orang"],
    ["注意", "zhù yì", "noticed", "perasan"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["踮起", "diǎn qǐ", "stood on", "menaikkan"],
    ["脚尖", "jiǎo jiān", "tiptoes", "hujung kaki"],
    ["，", "", "", ""],
    ["使", "shǐ", "making", "membuatkan"],
    ["矮小的", "ǎi xiǎo de", "short", "pendek"],
    ["身体", "shēn tǐ", "body", "badan"],
    ["挨蹭过", "āi cèng guò", "squeezed past", "merayap melewati"],
    ["别的", "bié de", "other", "lain"],
    ["顾客", "gù kè", "customers", "pelanggan"],
    ["和", "hé", "and", "dan"],
    ["书柜", "shū guì", "bookshelves", "rak buku"],
    ["的", "de", "", ""],
    ["夹缝", "jiā fèng", "gaps", "celah-celah"],
    ["，", "", "", ""],
    ["从", "cóng", "from", "dari"],
    ["大人", "dà rén", "adults", "orang dewasa"],
    ["的", "de", "", ""],
    ["腋下", "yè xià", "armpits", "bawah ketiak"],
    ["钻过去", "zuān guò qù", "squeezed through", "menyusup melewati"],
    ["。", "", "", ""],
    ["哟", "yō", "Oops", "Aduh"],
    ["，", "", "", ""],
    ["把", "bǎ", "", ""],
    ["头发", "tóu fa", "hair", "rambut"],
    ["弄乱了", "nòng luàn le", "messed up", "kusut"],
    ["，", "", "", ""],
    ["没关系", "méi guān xi", "never mind", "tak apa"],
    ["，", "", "", ""],
    ["我到底", "wǒ dào dǐ", "I finally", "saya akhirnya"],
    ["挤到", "jǐ dào", "squeezed to", "sampai ke"],
    ["里边", "lǐ biān", "inside", "dalam"],
    ["来了", "lái le", "", ""],
    ["。", "", "", ""],
    ["在", "zài", "among", "di"],
    ["一片", "yī piàn", "a sea of", "se lautan"],
    ["花绿", "huā lǜ", "colorful", "berwarna-warni"],
    ["封面", "fēng miàn", "covers", "kulit buku"],
    ["的", "de", "", ""],
    ["排列队", "pái liè duì", "arrangement", "susunan"],
    ["里", "lǐ", "in", "dalam"],
    ["，", "", "", ""],
    ["我的", "wǒ de", "my", "saya punya"],
    ["眼睛", "yǎn jīng", "eyes", "mata"],
    ["过于", "guò yú", "too", "terlalu"],
    ["急忙", "jí máng", "hurriedly", "cepat-cepat"],
    ["地", "de", "", ""],
    ["寻找", "xún zhǎo", "searching", "mencari"],
    ["，", "", "", ""],
    ["反而", "fǎn ér", "instead", "sebaliknya"],
    ["看不到", "kàn bù dào", "couldn't see", "tidak nampak"],
    ["那", "nà", "that", "itu"],
    ["本书", "běn shū", "book", "buku"],
    ["的", "de", "", ""],
    ["所在", "suǒ zài", "whereabouts", "di mana"],
    ["。", "", "", ""],
    ["从头", "cóng tóu", "from the beginning", "dari awal"],
    ["来", "lái", "again", "lagi"],
    ["，", "", "", ""],
    ["再", "zài", "again", "lagi"],
    ["数一遍", "shǔ yī biàn", "count once", "kira sekali"],
    ["。", "", "", ""],
    ["啊", "ā", "Ah", "Ah"],
    ["！", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["在", "zài", "is at", "di"],
    ["这里", "zhè lǐ", "here", "sini"],
    ["，", "", "", ""],
    ["原来", "yuán lái", "it turned out", "rupanya"],
    ["不是", "bú shì", "was not", "bukan"],
    ["在", "zài", "at", "di"],
    ["昨天", "zuó tiān", "yesterday's", "semalam"],
    ["那", "nà", "that", "itu"],
    ["位置", "wèi zhì", "position", "kedudukan"],
    ["了", "le", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    ["我", "wǒ", "I", "saya"],
    ["庆幸", "qìng xìng", "was glad", "bersyukur"],
    ["它", "tā", "it", "ia"],
    ["居然", "jū rán", "actually", "rupanya"],
    ["没有", "méi yǒu", "not", "tidak"],
    ["被", "bèi", "was", "telah"],
    ["卖出去", "mài chū qù", "sold", "terjual"],
    ["，", "", "", ""],
    ["仍", "réng", "still", "masih"],
    ["四平八稳地", "sì píng bā wěn de", "steadily", "dengan stabil"],
    ["躺在", "tǎng zài", "lying on", "terbaring di"],
    ["书架上", "shū jià shàng", "the shelf", "rak buku"],
    ["，", "", "", ""],
    ["专候", "zhuān hòu", "waiting for", "menunggu"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["光临", "guāng lín", "arrival", "kedatangan"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["多么", "duō me", "how", "begitu"],
    ["高兴", "gāo xìng", "happy", "gembira"],
    ["，", "", "", ""],
    ["又", "yòu", "and", "dan"],
    ["多么", "duō me", "how", "begitu"],
    ["渴望", "kě wàng", "eagerly", "rindu"],
    ["地", "de", "", ""],
    ["伸手", "shēn shǒu", "reached out", "menghulurkan tangan"],
    ["去拿", "qù ná", "to take", "untuk mengambil"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["和", "hé", "with", "dengan"],
    ["我的手", "wǒ de shǒu", "my hand", "tangan saya"],
    ["同时", "tóng shí", "at the same time", "pada masa yang sama"],
    ["抵达的", "dǐ dá de", "arrived", "tiba"],
    ["，", "", "", ""],
    ["还有", "hái yǒu", "there was also", "ada juga"],
    ["一双", "yī shuāng", "a pair of", "sepasang"],
    ["巨掌", "jù zhǎng", "huge palms", "tapak tangan besar"],
    ["，", "", "", ""],
    ["十个", "shí gè", "ten", "sepuluh"],
    ["手指", "shǒu zhǐ", "fingers", "jari"],
    ["大大地", "dà dà de", "widely", "dengan lebar"],
    ["分开来", "fēn kāi lái", "spread", "terbuka"],
    ["，", "", "", ""],
    ["压住了", "yā zhù le", "pressed down on", "menekan"],
    ["那", "nà", "that", "itu"],
    ["本书", "běn shū", "book", "buku"],
    ["的", "de", "", ""],
    ["整个", "zhěng gè", "whole", "keseluruhan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["到底", "dào dǐ", "after all", "akhirnya"],
    ["买", "mǎi", "buy", "beli"],
    ["不买", "bù mǎi", "not buy", "tak beli"],
    ["？”", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    ["声音", "shēng yīn", "The voice", "Suara"],
    ["不算小", "bú suàn xiǎo", "not soft", "tidak kecil"],
    ["，", "", "", ""],
    ["惊动了", "jīng dòng le", "startled", "mengejutkan"],
    ["其他", "qí tā", "other", "lain"],
    ["顾客", "gù kè", "customers", "pelanggan"],
    ["，", "", "", ""],
    ["他们", "tā men", "they", "mereka"],
    ["全部", "quán bù", "all", "semua"],
    ["回过头来", "huí guò tóu lái", "turned around", "menoleh ke belakang"],
    ["，", "", "", ""],
    ["面向着", "miàn xiàng zhe", "facing", "menghadap"],
    ["我", "wǒ", "me", "saya"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["像", "xiàng", "like", "seperti"],
    ["一个", "yī gè", "a", "seorang"],
    ["被捉到的", "bèi zhuō dào de", "caught", "yang tertangkap"],
    ["小偷", "xiǎo tōu", "thief", "pencuri"],
    ["，", "", "", ""],
    ["羞惭", "xiū cán", "ashamed", "malu"],
    ["而", "ér", "and", "dan"],
    ["尴尬", "gān gà", "embarrassed", "kekok"],
    ["，", "", "", ""],
    ["涨红了", "zhàng hóng le", "blushed", "muka merah"],
    ["脸", "liǎn", "face", "muka"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["抬起头", "tái qǐ tóu", "looked up", "mendongak"],
    ["，", "", "", ""],
    ["难堪地", "nán kān de", "awkwardly", "dengan kekok"],
    ["望着", "wàng zhe", "looked at", "memandang"],
    ["他", "tā", "him", "dia"],
    ["——", "", "", ""],
    ["那", "nà", "that", "itu"],
    ["书店", "shū diàn", "bookstore", "kedai buku"],
    ["的", "de", "", ""],
    ["老板", "lǎo bǎn", "owner", "tuan kedai"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["威风凛凛地", "wēi fēng lǐn lǐn de", "imposingly", "dengan gagah"],
    ["俯视着", "fǔ shì zhe", "looked down on", "memandang rendah"],
    ["我", "wǒ", "me", "saya"],
    ["。", "", "", ""],
    ["店", "diàn", "The shop", "Kedai"],
    ["是", "shì", "was", "ialah"],
    ["他的", "tā de", "his", "dia punya"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["有", "yǒu", "had", "ada"],
    ["全部", "quán bù", "every", "segala"],
    ["的", "de", "", ""],
    ["理由", "lǐ yóu", "right", "alasan"],
    ["用", "yòng", "to use", "guna"],
    ["这种", "zhè zhǒng", "this kind of", "jenis ini"],
    ["声气", "shēng qì", "tone", "nada"],
    ["对待", "duì dài", "treat", "perlakukan"],
    ["我", "wǒ", "me", "saya"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["用", "yòng", "with", "dengan"],
    ["几乎", "jī hū", "almost", "hampir"],
    ["要哭出来", "yào kū chū lái", "about to cry", "hampir menangis"],
    ["的", "de", "", ""],
    ["声音", "shēng yīn", "voice", "suara"],
    ["，", "", "", ""],
    ["悲愤地", "bēi fèn de", "indignantly", "dengan marah"],
    ["反抗了", "fǎn kàng le", "retorted", "menentang"],
    ["一句", "yī jù", "a sentence", "satu ayat"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["看看", "kàn kan", "Look", "Tengok"],
    ["都", "dōu", "even", "pun"],
    ["不行吗", "bù xíng ma", "not allowed", "tak boleh ke"],
    ["？”", "", "", ""],
    ["其实", "qí shí", "Actually", "Sebenarnya"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["声音", "shēng yīn", "voice", "suara"],
    ["是", "shì", "was", "ialah"],
    ["多么", "duō me", "so", "begitu"],
    ["软弱无力", "ruǎn ruò wú lì", "weak", "lemah"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    ["在", "zài", "Under", "Di"],
    ["众目睽睽", "zhòng mù kuí kuí", "public gaze", "pandangan ramai"],
    ["之下", "zhī xià", "under", "di bawah"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["几乎是", "jī hū shì", "almost", "hampir"],
    ["狼狈地", "láng bèi de", "awkwardly", "dengan kekok"],
    ["跨出了", "kuà chū le", "stepped out of", "melangkah keluar"],
    ["店门", "diàn mén", "shop door", "pintu kedai"],
    ["，", "", "", ""],
    ["脚跟", "jiǎo gēn", "my heels", "tumit"],
    ["后面", "hòu miàn", "behind", "di belakang"],
    ["紧跟着", "jǐn gēn zhe", "closely followed by", "diikuti rapat"],
    ["老板", "lǎo bǎn", "the boss's", "tuan kedai punya"],
    ["的", "de", "", ""],
    ["冷笑", "lěng xiào", "cold laugh", "ketawa dingin"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["不是", "bú shì", "Not", "Bukan"],
    ["一回", "yī huí", "first time", "kali pertama"],
    ["了", "le", "", ""],
    ["！”", "", "", ""],
    ["不是", "bú shì", "Not", "Bukan"],
    ["一回", "yī huí", "first time", "kali pertama"],
    ["了", "le", "", ""],
    ["？", "", "", ""],
    ["那", "nà", "That", "Itu"],
    ["口气", "kǒu qì", "tone", "nada"],
    ["对我", "duì wǒ", "to me", "terhadap saya"],
    ["还算", "hái suàn", "still", "masih"],
    ["是", "shì", "was", "ialah"],
    ["宽容的", "kuān róng de", "tolerant", "bertolak ansur"],
    ["，", "", "", ""],
    ["仿佛", "fǎng fú", "as if", "seolah-olah"],
    ["我", "wǒ", "I", "saya"],
    ["是", "shì", "were", "ialah"],
    ["一个", "yī gè", "a", "seorang"],
    ["不可以", "bù kě yǐ", "cannot", "tidak boleh"],
    ["再", "zài", "again", "lagi"],
    ["原谅的", "yuán liàng de", "forgivable", "dimaafkan"],
    ["惯贼", "guàn zéi", "habitual thief", "pencuri tegar"],
    ["。", "", "", ""],
    ["但", "dàn", "But", "Tetapi"],
    ["我", "wǒ", "I", "saya"],
    ["是", "shì", "did", "adakah"],
    ["偷窃了", "tōu qiè le", "steal", "mencuri"],
    ["什么", "shén me", "anything", "apa-apa"],
    ["吗", "ma", "", ""],
    ["？", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["不过", "bù guò", "merely", "hanyalah"],
    ["是", "shì", "was", "ialah"],
    ["一个", "yī gè", "a", "seorang"],
    ["无力", "wú lì", "unable", "tidak mampu"],
    ["购买", "gòu mǎi", "afford", "membeli"],
    ["而又", "ér yòu", "but", "tetapi"],
    ["渴望", "kě wàng", "longing", "ingin"],
    ["读到", "dú dào", "to read", "membaca"],
    ["那", "nà", "that", "itu"],
    ["本书", "běn shū", "book", "buku"],
    ["的", "de", "", ""],
    ["穷学生", "qióng xué sheng", "poor student", "pelajar miskin"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    ["曾经", "céng jīng", "once", "pernah"],
    ["有一天", "yǒu yī tiān", "one day", "suatu hari"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["偶然", "ǒu rán", "happened to", "kebetulan"],
    ["走过", "zǒu guò", "passed by", "melalui"],
    ["书店", "shū diàn", "bookstore", "kedai buku"],
    ["的", "de", "", ""],
    ["窗前", "chuāng qián", "window", "hadapan tingkap"],
    ["，", "", "", ""],
    ["窗里", "chuāng lǐ", "inside", "di dalam"],
    ["刚好", "gāng hǎo", "just", "tepat"],
    ["摆了几本", "bǎi le jǐ běn", "displayed a few", "terpamer beberapa"],
    ["慕名很久", "mù míng hěn jiǔ", "long-admired", "sudah lama dikagumi"],
    ["的", "de", "", ""],
    ["名著", "míng zhù", "masterpieces", "karya agung"],
    ["，", "", "", ""],
    ["欲望", "yù wàng", "desire", "keinginan"],
    ["推动着", "tuī dòng zhe", "drove", "mendorong"],
    ["我", "wǒ", "me", "saya"],
    ["，", "", "", ""],
    ["不由得", "bù yóu de", "couldn't help", "tanpa sedar"],
    ["走进", "zǒu jìn", "entered", "masuk ke"],
    ["书店", "shū diàn", "bookstore", "kedai buku"],
    ["，", "", "", ""],
    ["想", "xiǎng", "wanted to", "mahu"],
    ["打听", "dǎ tīng", "ask about", "bertanya"],
    ["一下", "yī xià", "", "tentang"],
    ["它的", "tā de", "its", "ia punya"],
    ["价钱", "jià qián", "price", "harga"],
    ["。", "", "", ""],
    ["也许", "yě xǔ", "Perhaps", "Mungkin"],
    ["是", "shì", "was", "ialah"],
    ["我", "wǒ", "I", "saya"],
    ["太矮小了", "tài ǎi xiǎo le", "too short", "terlalu pendek"],
    ["，", "", "", ""],
    ["不引人注意", "bù yǐn rén zhù yì", "didn't attract attention", "tidak menarik perhatian"],
    ["，", "", "", ""],
    ["竟", "jìng", "actually", "sebenarnya"],
    ["没有人", "méi yǒu rén", "no one", "tiada orang"],
    ["过来", "guò lái", "come over", "datang"],
    ["招呼", "zhāo hu", "serve", "melayan"],
    ["，", "", "", ""],
    ["我就", "wǒ jiù", "so I", "saya pun"],
    ["随便", "suí biàn", "casually", "sambil lalu"],
    ["翻开", "fān kāi", "opened", "buka"],
    ["一本", "yī běn", "a", "sebuah"],
    ["摆在", "bǎi zài", "placed on", "diletakkan di"],
    ["长桌上", "cháng zhuō shàng", "long table", "meja panjang"],
    ["的", "de", "", ""],
    ["书", "shū", "book", "buku"],
    ["，", "", "", ""],
    ["慢慢", "màn màn", "slowly", "perlahan-lahan"],
    ["读下去", "dú xià qù", "read on", "baca"],
    ["，", "", "", ""],
    ["读了", "dú le", "after reading", "selepas membaca"],
    ["一会儿", "yī huì r", "a while", "sebentar"],
    ["仍", "réng", "still", "masih"],
    ["没有人", "méi yǒu rén", "no one", "tiada orang"],
    ["理会", "lǐ huì", "pay attention", "peduli"],
    ["，", "", "", ""],
    ["而", "ér", "and", "dan"],
    ["书中的", "shū zhōng de", "the book's", "dalam buku"],
    ["故事", "gù shì", "story", "cerita"],
    ["已", "yǐ", "already", "sudah"],
    ["使我", "shǐ wǒ", "made me", "membuatkan saya"],
    ["全神贯注", "quán shén guàn zhù", "absorbed", "memikat perhatian"],
    ["，", "", "", ""],
    ["舍不得", "shě bu de", "couldn't bear to", "sayang"],
    ["放下了", "fàng xià le", "put down", "letakkan"],
    ["。", "", "", ""],
    ["直到", "zhí dào", "Until", "Sehingga"],
    ["好大工夫", "hǎo dà gōng fu", "a long time", "lama"],
    ["，", "", "", ""],
    ["才", "cái", "only then", "baru"],
    ["过来", "guò lái", "came over", "datang"],
    ["一位", "yī wèi", "a", "seorang"],
    ["店员", "diàn yuán", "shop assistant", "pekerja kedai"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["赶忙", "gǎn máng", "quickly", "cepat-cepat"],
    ["合起", "hé qǐ", "closed", "tutup"],
    ["书来", "shū lái", "the book", "buku"],
    ["递给", "dì gěi", "handed to", "beri"],
    ["他看", "tā kàn", "him to see", "dia lihat"],
    ["，", "", "", ""],
    ["煞有其事似的", "shà yǒu qí shì shì de", "pretending", "berpura-pura"],
    ["问他", "wèn tā", "asked him", "tanya dia"],
    ["价钱", "jià qián", "price", "harga"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["明知道", "míng zhī dào", "knew well", "tahu"],
    ["，", "", "", ""],
    ["任何", "rèn hé", "any", "apa-apa"],
    ["便宜", "pián yi", "cheap", "murah"],
    ["价钱", "jià qián", "price", "harga"],
    ["对于", "duì yú", "for", "bagi"],
    ["我", "wǒ", "me", "saya"],
    ["都是", "dōu shì", "were all", "semuanya"],
    ["枉然的", "wǎng rán de", "in vain", "sia-sia"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["绝没有", "jué méi yǒu", "absolutely had no", "langsung tiada"],
    ["多余的", "duō yú de", "extra", "lebihan"],
    ["钱", "qián", "money", "wang"],
    ["去买", "qù mǎi", "to buy", "untuk membeli"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    ["但是", "dàn shì", "But", "Tetapi"],
    ["自此以后", "zì cǐ yǐ hòu", "from then on", "sejak itu"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["得了", "dé le", "found", "mendapat"],
    ["一条", "yī tiáo", "a", "satu"],
    ["不费", "bù fèi", "without spending", "tanpa membelanjakan"],
    ["一文钱", "yī wén qián", "a penny", "sesen pun"],
    ["读书", "dú shū", "reading", "membaca"],
    ["的", "de", "", ""],
    ["门径", "mén jìng", "way", "cara"],
    ["。", "", "", ""],
    ["下课后", "xià kè hòu", "After class", "Selepas sekolah"],
    ["急忙", "jí máng", "hurriedly", "tergesa-gesa"],
    ["赶到", "gǎn dào", "went to", "pergi ke"],
    ["这条", "zhè tiáo", "this", "ini"],
    ["“", "", "", ""],
    ["文化街", "wén huà jiē", "Culture Street", "Jalan Budaya"],
    ["”", "", "", ""],
    ["，", "", "", ""],
    ["这里", "zhè lǐ", "here", "di sini"],
    ["书店", "shū diàn", "bookstores", "kedai buku"],
    ["林立", "lín lì", "stand like a forest", "bagaikan hutan"],
    ["，", "", "", ""],
    ["使我有", "shǐ wǒ yǒu", "giving me", "memberi saya"],
    ["更多的", "gèng duō de", "more", "lebih banyak"],
    ["机会", "jī huì", "opportunities", "peluang"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    ["一页", "yī yè", "One page", "Satu muka surat"],
    ["，", "", "", ""],
    ["两页", "liǎng yè", "two pages", "dua muka surat"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["如", "rú", "like", "seperti"],
    ["饥饿的", "jī è de", "hungry", "lapar"],
    ["瘦狼", "shòu láng", "lean wolf", "serigala kurus"],
    ["，", "", "", ""],
    ["贪婪地", "tān lán de", "greedily", "dengan rakus"],
    ["吞读下去", "tūn dú xià qù", "devouring", "membaca"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["很快乐", "hěn kuài lè", "very happy", "sangat gembira"],
    ["，", "", "", ""],
    ["也很惧怕", "yě hěn jù pà", "also very afraid", "juga sangat takut"],
    ["，", "", "", ""],
    ["这种", "zhè zhǒng", "this kind of", "jenis ini"],
    ["窃读的", "qiè dú de", "secret reading", "membaca secara curi"],
    ["滋味", "zī wèi", "feeling", "perasaan"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    ["有时", "yǒu shí", "Sometimes", "Kadang-kadang"],
    ["一本书", "yī běn shū", "a book", "sebuah buku"],
    ["我要", "wǒ yào", "I had to", "saya perlu"],
    ["分别到", "fēn bié dào", "go to different", "pergi ke beberapa"],
    ["几家", "jǐ jiā", "several", "beberapa"],
    ["书店", "shū diàn", "bookstores", "kedai buku"],
    ["去读完", "qù dú wán", "to finish reading", "untuk habiskan baca"],
    ["，", "", "", ""],
    ["比如", "bǐ rú", "for example", "contohnya"],
    ["当", "dāng", "when", "apabila"],
    ["我觉得", "wǒ jué de", "I felt", "saya rasa"],
    ["当时的", "dāng shí de", "the current", "pada masa itu"],
    ["环境", "huán jìng", "environment", "persekitaran"],
    ["已", "yǐ", "already", "sudah"],
    ["不适宜", "bù shì yí", "not suitable", "tidak sesuai"],
    ["我", "wǒ", "me", "saya"],
    ["在", "zài", "to", "di"],
    ["这家", "zhè jiā", "this", "ini"],
    ["书店", "shū diàn", "bookstore", "kedai buku"],
    ["站下去", "zhàn xià qù", "continue standing", "terus berdiri"],
    ["的话", "de huà", "", ""],
    ["，", "", "", ""],
    ["我便要", "wǒ biàn yào", "I would", "saya akan"],
    ["知趣地", "zhī qù de", "sensibly", "dengan bijak"],
    ["放下", "fàng xià", "put down", "letakkan"],
    ["书", "shū", "the book", "buku"],
    ["，", "", "", ""],
    ["若无其事地", "ruò wú qí shì de", "as if nothing happened", "seolah-olah tiada apa-apa"],
    ["走出去", "zǒu chū qù", "walk out", "keluar"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["再", "zài", "again", "lagi"],
    ["走入", "zǒu rù", "enter", "masuk ke"],
    ["另一家", "lìng yī jiā", "another", "kedai lain"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    ["我", "wǒ", "I", "saya"],
    ["希望到", "xī wàng dào", "hoped to go to", "berharap pergi ke"],
    ["顾客", "gù kè", "customers", "pelanggan"],
    ["正多着", "zhèng duō zhe", "many", "ramai"],
    ["的", "de", "", ""],
    ["书店", "shū diàn", "bookstore", "kedai buku"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["那样", "nà yàng", "that way", "dengan itu"],
    ["可以把", "kě yǐ bǎ", "could", "boleh"],
    ["矮小的", "ǎi xiǎo de", "short", "pendek"],
    ["我", "wǒ", "me", "saya"],
    ["挤进去", "jǐ jìn qù", "squeeze in", "menyusup masuk"],
    ["，", "", "", ""],
    ["而不致", "ér bù zhì", "without", "tanpa"],
    ["被人", "bèi rén", "being", "orang"],
    ["注意", "zhù yì", "noticed", "perasan"],
    ["。", "", "", ""],
    ["偶然", "ǒu rán", "Occasionally", "Kadang-kadang"],
    ["进来看书", "jìn lái kàn shū", "come in to read", "datang membaca"],
    ["的", "de", "", ""],
    ["人", "rén", "people", "orang"],
    ["虽然", "suī rán", "although", "walaupun"],
    ["很多", "hěn duō", "many", "ramai"],
    ["，", "", "", ""],
    ["但是", "dàn shì", "but", "tetapi"],
    ["像我这样", "xiàng wǒ zhè yàng", "like me", "seperti saya"],
    ["常常", "cháng cháng", "often", "sering"],
    ["光顾", "guāng gù", "visiting", "berkunjung"],
    ["而", "ér", "but", "tetapi"],
    ["从不", "cóng bù", "never", "tidak pernah"],
    ["买一本", "mǎi yī běn", "buy one", "beli sebatang"],
    ["的", "de", "", ""],
    ["，", "", "", ""],
    ["实在没有", "shí zài méi yǒu", "really none", "memang tiada"],
    ["。", "", "", ""],
    ["因此", "yīn cǐ", "Therefore", "Oleh itu"],
    ["我", "wǒ", "I", "saya"],
    ["要", "yào", "had to", "perlu"],
    ["把自己", "bǎ zì jǐ", "myself", "diri sendiri"],
    ["隐藏起来", "yǐn cáng qǐ lái", "hide", "menyembunyikan"],
    ["，", "", "", ""],
    ["真是", "zhēn shì", "truly", "benar-benar"],
    ["像", "xiàng", "like", "seperti"],
    ["个小偷", "gè xiǎo tōu", "a thief", "pencuri"],
    ["似的", "shì de", "", ""],
    ["。", "", "", ""],
    ["有时", "yǒu shí", "Sometimes", "Kadang-kadang"],
    ["我", "wǒ", "I", "saya"],
    ["贴在", "tiē zài", "stuck close to", "melekat di sisi"],
    ["一个", "yī gè", "a", "seorang"],
    ["大人的", "dà rén de", "adult's", "orang dewasa punya"],
    ["身边", "shēn biān", "side", "sisi"],
    ["，", "", "", ""],
    ["仿佛", "fǎng fú", "as if", "seolah-olah"],
    ["我是", "wǒ shì", "I was", "saya"],
    ["与他", "yǔ tā", "with him", "dengannya"],
    ["同来的", "tóng lái de", "together", "bersama"],
    ["小妹妹", "xiǎo mèi mei", "little sister", "adik"],
    ["或者", "huò zhě", "or", "atau"],
    ["女儿", "nǚ ér", "daughter", "anak perempuan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第12段

    ["最令人开心的", "zuì lìng rén kāi xīn de", "The most delightful", "Yang paling menggembirakan"],
    ["还是", "hái shì", "still is", "ialah"],
    ["下雨天", "xià yǔ tiān", "rainy days", "hari hujan"],
    ["，", "", "", ""],
    ["感谢", "gǎn xiè", "thanks to", "berterima kasih kepada"],
    ["雨水", "yǔ shuǐ", "rain", "hujan"],
    ["的", "de", "", ""],
    ["灌溉", "guàn gài", "irrigation", "siraman"],
    ["，", "", "", ""],
    ["越是", "yuè shì", "the more", "semakin"],
    ["倾盆大雨", "qīng pén dà yǔ", "heavy rain", "hujan lebat"],
    ["我越高兴", "wǒ yuè gāo xìng", "the happier I was", "semakin gembira saya"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["那时", "nà shí", "then", "pada masa itu"],
    ["我便有", "wǒ biàn yǒu", "I would have", "saya ada"],
    ["充足的", "chōng zú de", "sufficient", "yang cukup"],
    ["理由", "lǐ yóu", "reason", "alasan"],
    ["在", "zài", "to", "di"],
    ["书店", "shū diàn", "bookstore", "kedai buku"],
    ["待下去", "dāi xià qù", "stay", "terus berada"],
    ["。", "", "", ""],
    ["好像", "hǎo xiàng", "Like", "Seperti"],
    ["躲雨人", "duǒ yǔ rén", "someone taking shelter from rain", "orang yang berteduh"],
    ["偶然", "ǒu rán", "by chance", "kebetulan"],
    ["避雨", "bì yǔ", "taking shelter", "berteduh"],
    ["到", "dào", "at", "di"],
    ["人家的", "rén jiā de", "someone's", "orang punya"],
    ["屋檐下", "wū yán xià", "eaves", "bawah cucur atap"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["总不好意思", "zǒng bù hǎo yì si", "wouldn't have the heart to", "mesti tak sampai hati"],
    ["赶走吧", "gǎn zǒu ba", "chase away", "halau"],
    ["？", "", "", ""],
    ["我有时", "wǒ yǒu shí", "Sometimes I", "Saya kadang-kadang"],
    ["还要", "hái yào", "would even", "akan"],
    ["装着", "zhuāng zhe", "pretend", "berpura-pura"],
    ["皱起", "zhòu qǐ", "frown", "berkerut"],
    ["眉头", "méi tóu", "eyebrows", "dahi"],
    ["，", "", "", ""],
    ["不时", "bù shí", "from time to time", "kadang-kadang"],
    ["望着", "wàng zhe", "looking at", "memandang"],
    ["街心", "jiē xīn", "street", "jalan"],
    ["，", "", "", ""],
    ["好像说", "hǎo xiàng shuō", "as if to say", "seolah-olah berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["这雨", "zhè yǔ", "This rain", "Hujan ini"],
    ["，", "", "", ""],
    ["害得我", "hài de wǒ", "has stranded me", "menyebabkan saya"],
    ["回不去了", "huí bù qù le", "can't go back", "tak boleh pulang"],
    ["。”", "", "", ""],
    ["其实", "qí shí", "Actually", "Sebenarnya"],
    ["，", "", "", ""],
    ["我的心里", "wǒ de xīn lǐ", "in my heart", "dalam hati saya"],
    ["是", "shì", "was", "ialah"],
    ["怎样", "zěn yàng", "how", "betapa"],
    ["高兴地", "gāo xìng de", "joyfully", "gembiranya"],
    ["喊着", "hǎn zhe", "shouting", "berteriak"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["再大些", "zài dà xiē", "More, more", "Lebih lebat lagi"],
    ["！", "", "", ""],
    ["再大些", "zài dà xiē", "More, more", "Lebih lebat lagi"],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第13段

    ["但", "dàn", "But", "Tetapi"],
    ["我", "wǒ", "I", "saya"],
    ["也", "yě", "also", "juga"],
    ["不是", "bú shì", "was not", "bukan"],
    ["读书", "dú shū", "reading", "membaca"],
    ["能够", "néng gòu", "able to", "boleh"],
    ["废寝忘食", "fèi qǐn wàng shí", "forgetting meals and sleep", "lupa makan dan tidur"],
    ["的", "de", "", ""],
    ["人", "rén", "person", "orang"],
    ["，", "", "", ""],
    ["当", "dāng", "when", "apabila"],
    ["三阳春", "sān yáng chūn", "Sanyangchun", "Sanyangchun"],
    ["正上座", "zhèng shàng zuò", "was busy", "sedang sibuk"],
    ["，", "", "", ""],
    ["飘来", "piāo lái", "drifting over", "berbaur"],
    ["一阵阵", "yī zhèn zhèn", "waves of", "berkali-kali"],
    ["炒菜香", "chǎo cài xiāng", "fragrance of cooking", "bau masakan"],
    ["时", "shí", "when", "ketika"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["也", "yě", "also", "juga"],
    ["饿得", "è de", "so hungry", "lapar sehingga"],
    ["饥肠辘辘", "jī cháng lù lù", "stomach rumbling", "perut keroncong"],
    ["，", "", "", ""],
    ["那时", "nà shí", "then", "pada masa itu"],
    ["我", "wǒ", "I", "saya"],
    ["也不免", "yě bù miǎn", "couldn't help", "tidak dapat"],
    ["要做个", "yào zuò gè", "daydream", "berangan-angan"],
    ["白日梦", "bái rì mèng", "daydream", "angan-angan"],
    ["：", "", "", ""],
    ["如果", "rú guǒ", "If", "Jika"],
    ["袋中", "dài zhōng", "in the pocket", "dalam poket"],
    ["有钱", "yǒu qián", "had money", "ada wang"],
    ["该多么好", "gāi duō me hǎo", "how wonderful", "alangkah baiknya"],
    ["！", "", "", ""],
    ["到", "dào", "Go to", "Pergi ke"],
    ["三阳春", "sān yáng chūn", "Sanyangchun", "Sanyangchun"],
    ["吃碗", "chī wǎn", "eat a bowl of", "makan semangkuk"],
    ["热热的", "rè rè de", "hot", "panas"],
    ["排骨大面", "pái gǔ dà miàn", "pork rib noodles", "mi tulang rusuk"],
    ["，", "", "", ""],
    ["回来", "huí lái", "come back", "kembali"],
    ["这里", "zhè lǐ", "here", "sini"],
    ["已经", "yǐ jīng", "already", "sudah"],
    ["有人", "yǒu rén", "someone", "ada orang"],
    ["给", "gěi", "for", "untuk"],
    ["摆上", "bǎi shàng", "placed", "meletakkan"],
    ["一张", "yī zhāng", "a", "sebuah"],
    ["弹簧沙发", "tán huáng shā fā", "spring sofa", "sofa spring"],
    ["，", "", "", ""],
    ["坐上去", "zuò shàng qù", "sit on it", "duduk di atas"],
    ["舒舒服服地", "shū shū fú fú de", "comfortably", "dengan selesa"],
    ["接着看", "jiē zhe kàn", "continue reading", "sambung membaca"],
    ["。", "", "", ""],
    ["我的", "wǒ de", "My", "Saya punya"],
    ["腿", "tuǐ", "legs", "kaki"],
    ["真够酸了", "zhēn gòu suān le", "were really sore", "sungguh sakit"],
    ["，", "", "", ""],
    ["交替着", "jiāo tì zhe", "alternating", "berganti-ganti"],
    ["用一条腿", "yòng yī tiáo tuǐ", "using one leg", "menggunakan sebelah kaki"],
    ["支持", "zhī chí", "support", "menyokong"],
    ["另一条", "lìng yī tiáo", "the other", "sebelah lagi"],
    ["，", "", "", ""],
    ["有时", "yǒu shí", "sometimes", "kadang-kadang"],
    ["忘形地", "wàng xíng de", "unconsciously", "tanpa sedar"],
    ["撅着", "juē zhe", "sticking out", "membongkokkan"],
    ["屁股", "pì gu", "bottom", "punggung"],
    ["依赖在", "yī lài zài", "leaning against", "bersandar di"],
    ["书柜旁", "shū guì páng", "bookshelf", "rak buku"],
    ["，", "", "", ""],
    ["以求", "yǐ qiú", "to seek", "untuk"],
    ["暂时的", "zàn shí de", "temporary", "sementara"],
    ["休息", "xiū xī", "rest", "rehat"],
    ["。", "", "", ""],
    ["明明知道", "míng míng zhī dào", "Clearly knowing", "Jelas tahu"],
    ["回家", "huí jiā", "going home", "pulang ke rumah"],
    ["还有", "hái yǒu", "there was still", "masih ada"],
    ["一段路", "yī duàn lù", "a distance", "perjalanan"],
    ["程要走", "chéng yào zǒu", "to walk", "untuk berjalan"],
    ["，", "", "", ""],
    ["可是", "kě shì", "but", "tetapi"],
    ["求知的", "qiú zhī de", "the thirst for knowledge", "keinginan untuk ilmu"],
    ["欲望", "yù wàng", "desire", "keinginan"],
    ["这么迫切", "zhè me pò qiè", "so urgent", "begitu mendesak"],
    ["，", "", "", ""],
    ["使我", "shǐ wǒ", "making me", "membuatkan saya"],
    ["舍不得", "shě bu de", "unable to give up", "tidak sanggup"],
    ["放弃", "fàng qì", "give up", "melepaskan"],
    ["任何", "rèn hé", "any", "apa-apa"],
    ["捉住的", "zhuō zhù de", "caught", "yang diperolehi"],
    ["窃读", "qiè dú", "secret reading", "membaca secara curi"],
    ["机会", "jī huì", "opportunity", "peluang"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第14段

    ["为了", "wèi le", "In order to", "Untuk"],
    ["解决", "jiě jué", "solve", "menyelesaikan"],
    ["肚子的", "dù zi de", "stomach's", "perut punya"],
    ["饥饿", "jī è", "hunger", "kelaparan"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["又", "yòu", "again", "lagi"],
    ["想出", "xiǎng chū", "thought of", "fikirkan"],
    ["一个", "yī gè", "a", "satu"],
    ["好办法", "hǎo bàn fǎ", "good solution", "cara yang baik"],
    ["：", "", "", ""],
    ["临来时", "lín lái shí", "before coming", "sebelum datang"],
    ["买上", "mǎi shàng", "buy", "beli"],
    ["两个", "liǎng gè", "two", "dua"],
    ["铜板", "tóng bǎn", "coppers", "syiling tembaga"],
    ["（", "", "", ""],
    ["两个铜板或许有", "liǎng gè tóng bǎn huò xǔ yǒu", "two coppers perhaps", "dua syiling tembaga mungkin ada"],
    ["）", "", "", ""],
    ["的", "de", "", ""],
    ["花生米", "huā shēng mǐ", "peanuts", "kacang tanah"],
    ["放在", "fàng zài", "put in", "letakkan di"],
    ["制服", "zhì fú", "uniform", "uniform"],
    ["口袋里", "kǒu dài lǐ", "pocket", "poket"],
    ["。", "", "", ""],
    ["当", "dāng", "When", "Apabila"],
    ["智慧之田", "zhì huì zhī tián", "the field of wisdom", "ladang kebijaksanaan"],
    ["丰收", "fēng shōu", "harvests", "menuai"],
    ["，", "", "", ""],
    ["而", "ér", "and", "dan"],
    ["胃袋", "wèi dài", "stomach", "perut"],
    ["求救", "qiú jiù", "calls for help", "meminta bantuan"],
    ["的时候", "de shí hou", "when", "ketika"],
    ["，", "", "", ""],
    ["我便", "wǒ biàn", "I would", "saya akan"],
    ["从", "cóng", "from", "dari"],
    ["口袋里", "kǒu dài lǐ", "the pocket", "poket"],
    ["掏出", "tāo chū", "take out", "mengeluarkan"],
    ["花生米", "huā shēng mǐ", "peanuts", "kacang tanah"],
    ["来救急", "lái jiù jí", "to relieve", "untuk menyelamat"],
    ["。", "", "", ""],
    ["要注意的是", "yào zhù yì de shì", "What needs to be noted", "Yang perlu diingat"],
    ["，", "", "", ""],
    ["花生皮", "huā shēng pí", "peanut skins", "kulit kacang"],
    ["必须", "bì xū", "must", "mesti"],
    ["留在", "liú zài", "remain in", "tinggal dalam"],
    ["口袋里", "kǒu dài lǐ", "the pocket", "poket"],
    ["，", "", "", ""],
    ["回到家", "huí dào jiā", "returning home", "pulang ke rumah"],
    ["把", "bǎ", "", ""],
    ["口袋", "kǒu dài", "pocket", "poket"],
    ["翻过来", "fān guò lái", "turn inside out", "terbalikkan"],
    ["，", "", "", ""],
    ["细碎的", "xì suì de", "crushed", "yang hancur"],
    ["花生皮", "huā shēng pí", "peanut skins", "kulit kacang"],
    ["便", "biàn", "then", "lalu"],
    ["像", "xiàng", "like", "seperti"],
    ["雪花样地", "xuě huā yàng de", "snowflakes", "bunga salji"],
    ["飞落下来", "fēi luò xià lái", "flutter down", "berterbangan turun"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第15段

    ["但", "dàn", "But", "Tetapi"],
    ["在", "zài", "after", "selepas"],
    ["这次", "zhè cì", "this", "ini"],
    ["屈辱", "qū rǔ", "humiliation", "penghinaan"],
    ["之后", "zhī hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["我的", "wǒ de", "my", "saya punya"],
    ["小心灵", "xiǎo xīn líng", "young heart", "hati kecil"],
    ["确", "què", "indeed", "memang"],
    ["受了", "shòu le", "received", "mendapat"],
    ["创伤", "chuāng shāng", "hurt", "luka"],
    ["，", "", "", ""],
    ["我的", "wǒ de", "my", "saya punya"],
    ["因", "yīn", "due to", "kerana"],
    ["贫苦", "pín kǔ", "poverty", "kemiskinan"],
    ["而", "ér", "", ""],
    ["引起的", "yǐn qǐ de", "caused", "yang menyebabkan"],
    ["自卑感", "zì bēi gǎn", "inferiority", "perasaan rendah diri"],
    ["再次", "zài cì", "again", "lagi"],
    ["地", "de", "", ""],
    ["犯发", "fàn fā", "flared up", "timbul"],
    ["，", "", "", ""],
    ["而且", "ér qiě", "and also", "dan juga"],
    ["产生了", "chǎn shēng le", "generated", "timbul"],
    ["对", "duì", "towards", "terhadap"],
    ["人类的", "rén lèi de", "humanity's", "manusia punya"],
    ["仇恨", "chóu hèn", "hatred", "kebencian"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第16段

    ["我", "wǒ", "I", "saya"],
    ["不再", "bù zài", "no longer", "tidak lagi"],
    ["去", "qù", "go to", "pergi ke"],
    ["书店", "shū diàn", "bookstore", "kedai buku"],
    ["，", "", "", ""],
    ["许多次", "xǔ duō cì", "many times", "banyak kali"],
    ["我", "wǒ", "I", "saya"],
    ["经过", "jīng guò", "passed", "melalui"],
    ["文化街", "wén huà jiē", "Culture Street", "Jalan Budaya"],
    ["都", "dōu", "would", "akan"],
    ["狠心咬牙地", "hěn xīn yǎo yá de", "resolutely", "dengan tegas"],
    ["走过去", "zǒu guò qù", "walk past", "berjalan melewati"],
    ["。", "", "", ""],
    ["但", "dàn", "But", "Tetapi"],
    ["一次", "yī cì", "once", "sekali"],
    ["，", "", "", ""],
    ["两次", "liǎng cì", "twice", "dua kali"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["下意识地", "xià yì shí de", "subconsciously", "secara tidak sedar"],
    ["走向", "zǒu xiàng", "walked towards", "berjalan ke arah"],
    ["那", "nà", "that", "itu"],
    ["熟悉的", "shú xī de", "familiar", "biasa"],
    ["街", "jiē", "street", "jalan"],
    ["，", "", "", ""],
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["有一天", "yǒu yī tiān", "one day", "suatu hari"],
    ["，", "", "", ""],
    ["求知的", "qiú zhī de", "the thirst for knowledge", "keinginan untuk ilmu"],
    ["欲望", "yù wàng", "desire", "keinginan"],
    ["迫使", "pò shǐ", "forced", "memaksa"],
    ["我", "wǒ", "me", "saya"],
    ["再度", "zài dù", "again", "lagi"],
    ["地", "de", "", ""],
    ["停下来", "tíng xià lái", "stopped", "berhenti"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["仍愿", "réng yuàn", "still willing", "masih mahu"],
    ["一试", "yī shì", "to try", "mencuba"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["一本", "yī běn", "a", "sebuah"],
    ["新书", "xīn shū", "new book", "buku baharu"],
    ["的", "de", "", ""],
    ["出版", "chū bǎn", "publication", "penerbitan"],
    ["广告", "guǎng gào", "advertisement", "iklan"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["从", "cóng", "from", "dari"],
    ["报上", "bào shàng", "the newspaper", "akhbar"],
    ["知道", "zhī dào", "knew", "tahu"],
    ["好多天了", "hǎo duō tiān le", "for many days", "sudah beberapa hari"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第17段

    ["我", "wǒ", "I", "saya"],
    ["再施", "zài shī", "used again", "guna semula"],
    ["惯技", "guàn jì", "old trick", "taktik lama"],
    ["，", "", "", ""],
    ["又", "yòu", "again", "lagi"],
    ["把自己", "bǎ zì jǐ", "myself", "diri sendiri"],
    ["藏在", "cáng zài", "hid in", "sembunyi di"],
    ["书店", "shū diàn", "bookstore", "kedai buku"],
    ["的", "de", "", ""],
    ["一角", "yī jiǎo", "corner", "satu sudut"],
    ["。", "", "", ""],
    ["当我", "dāng wǒ", "When I", "Apabila saya"],
    ["翻开", "fān kāi", "opened", "buka"],
    ["第一页", "dì yī yè", "the first page", "halaman pertama"],
    ["时", "shí", "when", "ketika"],
    ["，", "", "", ""],
    ["心中", "xīn zhōng", "in my heart", "dalam hati"],
    ["不禁", "bù jīn", "couldn't help", "tidak dapat menahan"],
    ["轻轻", "qīng qīng", "softly", "perlahan-lahan"],
    ["呼道", "hū dào", "whisper", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["啊", "ā", "Ah", "Ah"],
    ["！", "", "", ""],
    ["终于", "zhōng yú", "Finally", "Akhirnya"],
    ["和你", "hé nǐ", "with you", "dengan awak"],
    ["相见", "xiāng jiàn", "meet", "berjumpa"],
    ["！”", "", "", ""],
    ["这是", "zhè shì", "This was", "Ini adalah"],
    ["一本", "yī běn", "a", "sebuah"],
    ["畅销书", "chàng xiāo shū", "bestseller", "buku laris"],
    ["，", "", "", ""],
    ["那么", "nà me", "so", "begitu"],
    ["厚厚的", "hòu hòu de", "thick", "tebal"],
    ["一册", "yī cè", "a volume", "satu jilid"],
    ["，", "", "", ""],
    ["拿在手里", "ná zài shǒu lǐ", "held in the hand", "dipegang di tangan"],
    ["，", "", "", ""],
    ["看在眼里", "kàn zài yǎn lǐ", "seen with the eyes", "dilihat dengan mata"],
    ["，", "", "", ""],
    ["多够分量", "duō gòu fèn liàng", "how substantial", "begitu bernilai"],
    ["！", "", "", ""],
    ["受了", "shòu le", "Having learned from", "Setelah belajar daripada"],
    ["前次的", "qián cì de", "last time's", "kali lepas punya"],
    ["教训", "jiào xùn", "lesson", "pengajaran"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["更小心地", "gèng xiǎo xīn de", "more carefully", "lebih berhati-hati"],
    ["不敢", "bù gǎn", "dare not", "tidak berani"],
    ["贪懒", "tān lǎn", "be lazy", "malas"],
    ["，", "", "", ""],
    ["多串", "duō chuàn", "visit more", "kunjungi lebih"],
    ["十几家", "shí jǐ jiā", "more than ten", "lebih sepuluh"],
    ["书店", "shū diàn", "bookstores", "kedai buku"],
    ["更妥当些", "gèng tuǒ dāng xiē", "more appropriate", "lebih sesuai"],
    ["，", "", "", ""],
    ["免得", "miǎn de", "to avoid", "untuk mengelakkan"],
    ["再遭遇到", "zài zāo yù dào", "encountering again", "menghadapi lagi"],
    ["前次的", "qián cì de", "previous", "kali lepas"],
    ["难堪", "nán kān", "embarrassment", "kemaluan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第18段

    ["每次", "měi cì", "Every time", "Setiap kali"],
    ["从", "cóng", "from", "dari"],
    ["书店", "shū diàn", "bookstore", "kedai buku"],
    ["出来", "chū lái", "came out", "keluar"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["都", "dōu", "all", "semua"],
    ["像", "xiàng", "like", "seperti"],
    ["喝醉了酒", "hē zuì le jiǔ", "drunk", "mabuk"],
    ["似的", "shì de", "", ""],
    ["，", "", "", ""],
    ["脑子", "nǎo zi", "my mind", "fikiran"],
    ["被", "bèi", "by", "oleh"],
    ["书中的", "shū zhōng de", "the book's", "dalam buku"],
    ["人物", "rén wù", "characters", "watak-watak"],
    ["所扰", "suǒ rǎo", "disturbed", "terganggu"],
    ["，", "", "", ""],
    ["踉踉跄跄", "liàng liàng qiàng qiàng", "staggering", "terhuyung-hayang"],
    ["，", "", "", ""],
    ["走路", "zǒu lù", "walking", "berjalan"],
    ["失去", "shī qù", "lost", "hilang"],
    ["控制", "kòng zhì", "control", "kawalan"],
    ["的", "de", "", ""],
    ["能力", "néng lì", "ability", "kebolehan"],
    ["。", "", "", ""],
    ["“", "", "", ""],
    ["明天", "míng tiān", "Tomorrow", "Esok"],
    ["早些来", "zǎo xiē lái", "come earlier", "datang lebih awal"],
    ["，", "", "", ""],
    ["可以", "kě yǐ", "can", "boleh"],
    ["全部", "quán bù", "all", "semua"],
    ["看完了", "kàn wán le", "finish reading", "habiskan baca"],
    ["。”", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["告诉", "gào su", "told", "memberitahu"],
    ["自己", "zì jǐ", "myself", "diri sendiri"],
    ["。", "", "", ""],
    ["想到", "xiǎng dào", "Thinking of", "Terfikir tentang"],
    ["明天", "míng tiān", "tomorrow", "esok"],
    ["仍", "réng", "still", "masih"],
    ["可以", "kě yǐ", "could", "boleh"],
    ["占有", "zhàn yǒu", "occupy", "menduduki"],
    ["书店", "shū diàn", "bookstore", "kedai buku"],
    ["的", "de", "", ""],
    ["一角", "yī jiǎo", "corner", "sudut"],
    ["时", "shí", "when", "ketika"],
    ["，", "", "", ""],
    ["被", "bèi", "by", "oleh"],
    ["快乐", "kuài lè", "joy", "kegembiraan"],
    ["激动的", "jī dòng de", "excited", "teruja"],
    ["忘形之躯", "wàng xíng zhī qū", "body forgetting itself", "tubuh yang tidak sedarkan diri"],
    ["，", "", "", ""],
    ["便", "biàn", "then", "lalu"],
    ["险些", "xiǎn xiē", "nearly", "hampir"],
    ["撞到", "zhuàng dào", "bumped into", "terlanggar"],
    ["树干上去", "shù gàn shàng qù", "tree trunk", "batang pokok"],
    ["。", "", "", ""]

    ["\n", "", "", ""], // 👈 第19段

    ["可是", "kě shì", "But", "Tetapi"],
    ["第二天", "dì èr tiān", "the next day", "esoknya"],
    ["走过", "zǒu guò", "after passing", "selepas melalui"],
    ["几家", "jǐ jiā", "several", "beberapa"],
    ["书店", "shū diàn", "bookstores", "kedai buku"],
    ["都", "dōu", "all", "semua"],
    ["看不见", "kàn bù jiàn", "couldn't see", "tidak nampak"],
    ["那", "nà", "that", "itu"],
    ["本书", "běn shū", "book", "buku"],
    ["时", "shí", "when", "ketika"],
    ["，", "", "", ""],
    ["像", "xiàng", "like", "seperti"],
    ["在手中", "zài shǒu zhōng", "in hand", "di tangan"],
    ["正看得起劲", "zhèng kàn de qǐ jìn", "reading enthusiastically", "sedang membaca dengan tekun"],
    ["的", "de", "", ""],
    ["书", "shū", "book", "buku"],
    ["被人抢去", "bèi rén qiǎng qù", "snatched away", "dirampas orang"],
    ["一样", "yī yàng", "", ""],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["暗暗", "àn àn", "secretly", "dalam hati"],
    ["焦急", "jiāo jí", "anxious", "cemas"],
    ["，", "", "", ""],
    ["并且", "bìng qiě", "and", "dan"],
    ["诅咒地", "zǔ zhòu de", "resentfully", "dengan rasa marah"],
    ["想", "xiǎng", "thought", "berfikir"],
    ["：", "", "", ""],
    ["皆因", "jiē yīn", "All because of", "Semuanya kerana"],
    ["没有钱", "méi yǒu qián", "no money", "tiada wang"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["不能", "bù néng", "couldn't", "tidak boleh"],
    ["占有", "zhàn yǒu", "have", "memiliki"],
    ["读书的", "dú shū de", "reading's", "membaca punya"],
    ["全部", "quán bù", "all", "segala"],
    ["快乐", "kuài lè", "joy", "kegembiraan"],
    ["，", "", "", ""],
    ["世上", "shì shàng", "in the world", "di dunia"],
    ["有钱的人", "yǒu qián de rén", "rich people", "orang kaya"],
    ["这样多", "zhè yàng duō", "so many", "begitu ramai"],
    ["，", "", "", ""],
    ["他们", "tā men", "they", "mereka"],
    ["把", "bǎ", "", ""],
    ["书", "shū", "books", "buku"],
    ["买光了", "mǎi guāng le", "bought up", "habiskan beli"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第20段

    ["我", "wǒ", "I", "saya"],
    ["惨淡无神地", "cǎn dàn wú shén de", "dejectedly", "dengan muram"],
    ["提着", "tí zhe", "carrying", "membawa"],
    ["书包", "shū bāo", "schoolbag", "beg sekolah"],
    ["，", "", "", ""],
    ["抱着", "bào zhe", "with", "dengan"],
    ["绝望的", "jué wàng de", "despair", "putus asa"],
    ["心情", "xīn qíng", "mood", "perasaan"],
    ["走进", "zǒu jìn", "entered", "masuk ke"],
    ["最末", "zuì mò", "last", "terakhir"],
    ["一家", "yī jiā", "a", "sebuah"],
    ["书店", "shū diàn", "bookstore", "kedai buku"],
    ["。", "", "", ""],
    ["昨天", "zuó tiān", "Yesterday", "Semalam"],
    ["在这里", "zài zhè lǐ", "here", "di sini"],
    ["看书时", "kàn shū shí", "when reading", "semasa membaca"],
    ["，", "", "", ""],
    ["已经", "yǐ jīng", "already", "sudah"],
    ["剩下", "shèng xià", "left", "tinggal"],
    ["最后一册", "zuì hòu yī cè", "the last copy", "naskhah terakhir"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["可不是", "kě bú shì", "indeed", "memang"],
    ["，", "", "", ""],
    ["看见", "kàn jiàn", "I saw", "nampak"],
    ["书架上", "shū jià shàng", "on the shelf", "di rak"],
    ["那", "nà", "that", "itu"],
    ["本书", "běn shū", "book", "buku"],
    ["的", "de", "", ""],
    ["位置", "wèi zhì", "spot", "kedudukan"],
    ["换了", "huàn le", "replaced by", "diganti dengan"],
    ["另外的书", "lìng wài de shū", "another book", "buku lain"],
    ["，", "", "", ""],
    ["心", "xīn", "my heart", "hati"],
    ["整个", "zhěng gè", "completely", "seluruhnya"],
    ["沉下了", "chén xià le", "sank", "jatuh"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第21段

    ["正在这时", "zhèng zài zhè shí", "At that moment", "Pada masa ini"],
    ["，", "", "", ""],
    ["一个", "yī gè", "a", "seorang"],
    ["耳朵上", "ěr duǒ shàng", "on his ear", "di telinga"],
    ["架着", "jià zhe", "with", "ada"],
    ["铅笔", "qiān bǐ", "pencil", "pensel"],
    ["的", "de", "", ""],
    ["店员", "diàn yuán", "shop assistant", "pekerja kedai"],
    ["走过来了", "zǒu guò lái le", "came over", "datang"],
    ["，", "", "", ""],
    ["看那样子", "kàn nà yàng zi", "it seemed", "nampaknya"],
    ["是", "shì", "was", "ialah"],
    ["来招呼", "lái zhāo hu", "to serve", "untuk melayan"],
    ["我的", "wǒ de", "me", "saya"],
    ["（", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["多么怕", "duō me pà", "how I feared", "betapa takut"],
    ["受人", "shòu rén", "being", "dilayan"],
    ["招待", "zhāo dài", "served", "orang"],
    ["！", "", "", ""],
    ["）", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["慌忙", "huāng máng", "hurriedly", "cepat-cepat"],
    ["把", "bǎ", "", ""],
    ["眼睛", "yǎn jīng", "eyes", "mata"],
    ["送上了", "sòng shàng le", "averted to", "alihkan ke"],
    ["书架", "shū jià", "bookshelf", "rak buku"],
    ["，", "", "", ""],
    ["装作", "zhuāng zuò", "pretending", "berpura-pura"],
    ["没看见", "méi kàn jiàn", "not to see", "tidak nampak"],
    ["。", "", "", ""],
    ["但是", "dàn shì", "But", "Tetapi"],
    ["一本书", "yī běn shū", "a book", "sebuah buku"],
    ["触着", "chù zhe", "touched", "menyentuh"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["胳膊", "gē bo", "arm", "lengan"],
    ["，", "", "", ""],
    ["轻轻地", "qīng qīng de", "gently", "perlahan-lahan"],
    ["送到", "sòng dào", "delivered to", "dihantar ke"],
    ["我的面前", "wǒ de miàn qián", "in front of me", "hadapan saya"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["请看吧", "qǐng kàn ba", "Please read", "Sila baca"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["多留了", "duō liú le", "kept an extra", "simpan tambahan"],
    ["一天", "yī tiān", "one day", "sehari"],
    ["没有卖", "méi yǒu mài", "without selling", "tanpa menjual"],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第22段

    ["啊", "ā", "Ah", "Ah"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["接过", "jiē guò", "took", "terima"],
    ["书", "shū", "the book", "buku"],
    ["害羞得", "hài xiū de", "too shy to", "malu sehingga"],
    ["不知", "bù zhī", "didn't know", "tidak tahu"],
    ["应当", "yīng dāng", "how to", "bagaimana"],
    ["如何", "rú hé", "how", "bagaimana"],
    ["对他", "duì tā", "to him", "kepadanya"],
    ["表示", "biǎo shì", "express", "menyatakan"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["感激", "gǎn jī", "gratitude", "terima kasih"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["却", "què", "but", "tetapi"],
    ["若无其事地", "ruò wú qí shì de", "as if nothing happened", "seolah-olah tiada apa-apa"],
    ["走开了", "zǒu kāi le", "walked away", "pergi"],
    ["。", "", "", ""],
    ["被", "bèi", "Overwhelmed by", "Dilanda"],
    ["冲动的", "chōng dòng de", "overwhelming", "yang kuat"],
    ["情感", "qíng gǎn", "emotion", "perasaan"],
    ["，", "", "", ""],
    ["使", "shǐ", "made", "membuatkan"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["眼光", "yǎn guāng", "gaze", "pandangan"],
    ["久久", "jiǔ jiǔ", "for a long time", "lama"],
    ["不能", "bù néng", "could not", "tidak boleh"],
    ["集中在", "jí zhōng zài", "concentrate on", "menumpu pada"],
    ["书本上", "shū běn shàng", "the book", "buku"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第23段

    ["当", "dāng", "When", "Apabila"],
    ["书店", "shū diàn", "the bookstore's", "kedai buku punya"],
    ["的", "de", "", ""],
    ["日光灯", "rì guāng dēng", "fluorescent lights", "lampu pendarfluor"],
    ["忽地", "hū de", "suddenly", "tiba-tiba"],
    ["亮了起来", "liàng le qǐ lái", "came on", "menyala"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["才", "cái", "only then", "baru"],
    ["觉出", "jué chū", "realized", "sedar"],
    ["站在这里", "zhàn zài zhè lǐ", "standing here", "berdiri di sini"],
    ["读了", "dú le", "reading for", "membaca selama"],
    ["两个钟点了", "liǎng gè zhōng diǎn le", "two hours", "dua jam"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["合上", "hé shàng", "closed", "tutup"],
    ["最后一页", "zuì hòu yī yè", "the last page", "halaman terakhir"],
    ["——", "", "", ""],
    ["咽了", "yàn le", "swallowed", "menelan"],
    ["一口唾沫", "yī kǒu tuò mò", "a mouthful of saliva", "air liur"],
    ["，", "", "", ""],
    ["好像", "hǎo xiàng", "as if", "seolah-olah"],
    ["所有的", "suǒ yǒu de", "all", "segala"],
    ["智慧", "zhì huì", "wisdom", "kebijaksanaan"],
    ["都", "dōu", "all", "semua"],
    ["被", "bèi", "were", "telah"],
    ["我", "wǒ", "me", "saya"],
    ["吞食下去了", "tūn shí xià qù le", "devoured", "ditelan"],
    ["。", "", "", ""],
    ["然后", "rán hòu", "Then", "Kemudian"],
    ["抬头", "tái tóu", "looked up", "mendongak"],
    ["找寻", "zhǎo xún", "to find", "mencari"],
    ["那", "nà", "that", "itu"],
    ["耳朵上", "ěr duǒ shàng", "on his ear", "di telinga"],
    ["架着铅笔", "jià zhe qiān bǐ", "with a pencil", "ada pensel"],
    ["的人", "de rén", "man", "orang"],
    ["，", "", "", ""],
    ["好", "hǎo", "to", "untuk"],
    ["交还", "jiāo huán", "return", "memulangkan"],
    ["他", "tā", "him", "dia"],
    ["这本书", "zhè běn shū", "this book", "buku ini"],
    ["。", "", "", ""],
    ["在", "zài", "At", "Di"],
    ["远远的", "yuǎn yuǎn de", "far", "jauh"],
    ["柜台旁", "guì tái páng", "counter", "kaunter"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["向我", "xiàng wǒ", "to me", "kepada saya"],
    ["轻轻地", "qīng qīng de", "gently", "perlahan-lahan"],
    ["点点头", "diǎn diǎn tóu", "nodded", "mengangguk"],
    ["，", "", "", ""],
    ["表示", "biǎo shì", "indicating", "menunjukkan"],
    ["他已经", "tā yǐ jīng", "he had already", "dia sudah"],
    ["知道", "zhī dào", "knew", "tahu"],
    ["我看完了", "wǒ kàn wán le", "I had finished", "saya sudah habis baca"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["默默地", "mò mò de", "quietly", "senyap-senyap"],
    ["把书", "bǎ shū", "the book", "buku"],
    ["放回", "fàng huí", "put back", "letakkan kembali"],
    ["书架上", "shū jià shàng", "on the shelf", "di rak"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第24段

    ["我", "wǒ", "I", "saya"],
    ["低着头", "dī zhe tóu", "with my head down", "dengan menunduk"],
    ["走出去", "zǒu chū qù", "walked out", "berjalan keluar"],
    ["（", "", "", ""],
    ["书店", "shū diàn", "bookstore", "kedai buku"],
    ["）", "", "", ""],
    ["，", "", "", ""],
    ["黑色", "hēi sè", "Black", "Hitam"],
    ["多皱的", "duō zhòu de", "wrinkled", "berkedut"],
    ["布裙", "bù qún", "cloth skirt", "skirt kain"],
    ["被", "bèi", "was", "telah"],
    ["风吹开来", "fēng chuī kāi lái", "blown open by the wind", "ditiup angin"],
    ["，", "", "", ""],
    ["像", "xiàng", "like", "seperti"],
    ["一把", "yī bǎ", "a", "sebuah"],
    ["支不开的", "zhī bù kāi de", "can't open", "tidak boleh dibuka"],
    ["破伞", "pò sǎn", "broken umbrella", "payung buruk"],
    ["，", "", "", ""],
    ["可是", "kě shì", "but", "tetapi"],
    ["我", "wǒ", "I", "saya"],
    ["浑身", "hún shēn", "my whole body", "seluruh badan"],
    ["都", "dōu", "all", "semua"],
    ["松快了", "sōng kuài le", "felt relaxed", "berasa lega"],
    ["。", "", "", ""],
    ["摸摸", "mō mō", "I felt", "saya raba"],
    ["口袋", "kǒu dài", "pocket", "poket"],
    ["，", "", "", ""],
    ["里面", "lǐ miàn", "inside", "di dalam"],
    ["是", "shì", "was", "ialah"],
    ["一包", "yī bāo", "a pack of", "sebungkus"],
    ["忘记吃的", "wàng jì chī de", "forgotten", "lupa dimakan"],
    ["花生米", "huā shēng mǐ", "peanuts", "kacang tanah"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["拿一粒", "ná yī lì", "took one", "ambil sebutir"],
    ["花生米", "huā shēng mǐ", "peanut", "kacang tanah"],
    ["送进", "sòng jìn", "put into", "masukkan ke"],
    ["嘴里", "zuǐ lǐ", "my mouth", "mulut"],
    ["，", "", "", ""],
    ["忽然", "hū rán", "suddenly", "tiba-tiba"],
    ["想起", "xiǎng qǐ", "remembered", "teringat"],
    ["有一次", "yǒu yī cì", "once", "pada suatu ketika"],
    ["国文先生", "guó wén xiān sheng", "the Chinese teacher", "guru Bahasa Cina"],
    ["鼓励", "gǔ lì", "encouraged", "menggalakkan"],
    ["我们", "wǒ men", "us", "kami"],
    ["用功", "yòng gōng", "to study hard", "belajar bersungguh"],
    ["的话", "de huà", "words", "kata-kata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["记住", "jì zhù", "Remember", "Ingat"],
    ["，", "", "", ""],
    ["你是", "nǐ shì", "You", "Awak"],
    ["吃饭", "chī fàn", "by eating", "dengan makan"],
    ["长大", "zhǎng dà", "grow up", "membesar"],
    ["，", "", "", ""],
    ["也是", "yě shì", "and also", "dan juga"],
    ["读书", "dú shū", "by reading", "dengan membaca"],
    ["长大的", "zhǎng dà de", "grow up", "membesar"],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第25段

    ["但是", "dàn shì", "But", "Tetapi"],
    ["今天", "jīn tiān", "today", "hari ini"],
    ["我", "wǒ", "I", "saya"],
    ["发现", "fā xiàn", "discovered", "mendapati"],
    ["这句话", "zhè jù huà", "this sentence", "ayat ini"],
    ["还", "hái", "still", "masih"],
    ["不够用", "bù gòu yòng", "is not enough", "tidak mencukupi"],
    ["，", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["应当", "yīng dāng", "should", "patut"],
    ["这么说", "zhè me shuō", "be said like this", "berkata begini"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["记住", "jì zhù", "Remember", "Ingat"],
    ["，", "", "", ""],
    ["你是", "nǐ shì", "You", "Awak"],
    ["吃饭", "chī fàn", "by eating", "dengan makan"],
    ["长大", "zhǎng dà", "grow up", "membesar"],
    ["，", "", "", ""],
    ["读书", "dú shū", "by reading", "dengan membaca"],
    ["长大", "zhǎng dà", "grow up", "membesar"],
    ["，", "", "", ""],
    ["也是", "yě shì", "and also", "dan juga"],
    ["在爱里", "zài ài lǐ", "in love", "dalam kasih sayang"],
    ["长大的", "zhǎng dà de", "grow up", "membesar"],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["林海音", "lín hǎi yīn", "Lin Haiyin", "Lin Haiyin"],
    ["《", "", "", ""],
    ["窃读记", "qiè dú jì", "Secret Reading", "Membaca Secara Curi"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
